AWSTemplateFormatVersion: 2010-09-09
Description: >-
  sam-gamify-gtasks
Transform:
  - AWS::Serverless-2016-10-31

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  ScheduledGoogleTasksProcessor:
    Type: AWS::Serverless::Function
    Properties:
      Description: A Lambda function that processes Google Tasks and sends a report via SES to the user's email at 10pm UTC.
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      Handler: src/handlers/scheduled-google-tasks-processor.scheduledGoogleTasksProcessorHandler

      Environment:
        Variables:
          GOOGLE_CLIENT_ID: "{{resolve:secretsmanager:gamify-gtasks:SecretString:GOOGLE_CLIENT_ID}}"
          GOOGLE_CLIENT_SECRET: "{{resolve:secretsmanager:gamify-gtasks:SecretString:GOOGLE_CLIENT_SECRET}}"
          SES_FROM_EMAIL: "{{resolve:secretsmanager:gamify-gtasks:SecretString:SES_FROM_EMAIL}}"
          SES_TO_EMAIL: "{{resolve:secretsmanager:gamify-gtasks:SecretString:SES_TO_EMAIL}}"

      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - ses:SendEmail
                - ses:SendRawEmail
              Resource: "*"

      Events:
        DailyTrigger:
          Type: Schedule
          Properties:
            Schedule: cron(0 22 * * ? *)
      MemorySize: 128
      Timeout: 100
